<a href="https://colab.research.google.com/github/AnkitAs98k/Heart-Disease-predictor/blob/main/cropPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [7]:
df1 = pd.read_csv('crop_yield.csv')
df2 = pd.read_csv('state_weather_data_1997_2020.csv')
df3 = pd.read_csv('state_soil_data.csv')

In [9]:
result1 = pd.merge(df1, df2, on='state', how='inner')
result1.head()

,crop,year_x,season,state,area,production,fertilizer,pesticide,yield,year_y,avg_temp_c,total_rainfall_mm,avg_humidity_percent
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1997,22.41,1468.92,70.71
1,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1998,22.98,1701.15,73.03
2,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1999,23.26,1622.42,71.99
3,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,2000,22.37,1958.50,75.29
4,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,2001,22.72,1808.20,74.66

In [11]:
df = pd.merge(result1,df3,on='state',how='inner')
df.head()

,crop,year_x,season,state,area,production,fertilizer,pesticide,yield,year_y,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1997,22.41,1468.92,70.71,60,18,38,5.8
1,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1998,22.98,1701.15,73.03,60,18,38,5.8
2,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,1999,23.26,1622.42,71.99,60,18,38,5.8
3,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,2000,22.37,1958.50,75.29,60,18,38,5.8
4,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,2001,22.72,1808.20,74.66,60,18,38,5.8

In [12]:
print(list(df.columns))

['crop', 'year_x', 'season', 'state', 'area', 'production', 'fertilizer', 'pesticide', 'yield', 'year_y', 'avg_temp_c', 'total_rainfall_mm', 'avg_humidity_percent', 'N', 'P', 'K', 'pH']

In [ ]:
sns.boxplot(df,)